language: generic

services:
  - docker

before_install:
  - docker build -t fidelisclayton/docker-react-tutorial  -f Dockerfile.dev .

script:
  - docker run -e CI=true fidelisclayton/docker-react-tutorial npm run test
