language: generic

services:
  - docker

before_install:
  - docker build -t fidelisclayton/docker-react-tutorial  -f Dockerfile.dev .

script:
  - docker run -e CI=true fidelisclayton/docker-react-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-tutorial"
  env: "DockerReactTutorial-env"
  bucket_name: "elasticbeanstalk-eu-central-1-173256646796"
  bucket_path: "docker-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
